### ISSUE TITLE
Error in running test example

### ISSUE THREAD

**Issue by haze1986** [BrianOBlanton/HycomTracker#1]
Hi I've downloaded and checked that nctoolbox and hycomtracker are both correct. When I run the example code it managed to run the loading time level XXX, and them integrating: [Date] and shows the red dots motion. Then it terminates with an error:

Attempted to access it1(1); index out of bounds because numel(it1)=0.

Error in drog2ddt>vel_interp (line 386)
it1=it1(1);

Error in drog2ddt>track2 (line 293)
    [uk2,vk2]=vel_interp(TheGrid,xtemp,ytemp,jtemp,V,timevec,t+.5*dt/24);

Error in drog2ddt (line 215)
   [xnext,ynext,jnext]=track2(TheGrid,jgood,xgood,ygood,V,timevec,time,dtsecs);

Error in HycomTracker (line 86)
[R.xx,R.yy,R.tt,R.uu,R.vv]=drog2ddt(G,tstart,tend,dt,stride,IC.x,IC.y,V,options);

Error in test (line 10)
R=HycomTracker(V,G,IC);

**Comment by BrianOBlanton** [comment]
there was a bug in the timestepping.  should be fixed now.
